/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': 'var(--wm-inverse-on-surface)',
        primary: 'var(--wm-primary)',
        outline: 'var(--wm-outline)',
        'surface-tint': 'var(--wm-surface-tint)',
        error: 'var(--wm-error)',
        'surface-variant': 'var(--wm-surface-variant)',
        secondary: 'var(--wm-secondary)',
        'on-surface-variant': 'var(--wm-on-surface-variant)',
        'surface-dim': 'var(--wm-surface-dim)',
        'on-tertiary-container': 'var(--wm-on-tertiary-container)',
        'on-primary-fixed': 'var(--wm-on-primary-fixed)',
        'outline-variant': 'var(--wm-outline-variant)',
        'on-primary-fixed-variant': 'var(--wm-on-primary-fixed-variant)',
        'surface-container': 'var(--wm-surface-container)',
        'inverse-primary': 'var(--wm-inverse-primary)',
        tertiary: 'var(--wm-tertiary)',
        'secondary-container': 'var(--wm-secondary-container)',
        'on-surface': 'var(--wm-on-surface)',
        'on-error': 'var(--wm-on-error)',
        background: 'var(--wm-background)',
        'surface-container-high': 'var(--wm-surface-container-high)',
        'surface-bright': 'var(--wm-surface-bright)',
        'on-secondary-container': 'var(--wm-on-secondary-container)',
        'primary-container': 'var(--wm-primary-container)',
        'surface-container-low': 'var(--wm-surface-container-low)',
        'on-tertiary': 'var(--wm-on-tertiary)',
        'primary-fixed': 'var(--wm-primary-fixed)',
        'primary-fixed-dim': 'var(--wm-primary-fixed-dim)',
        'tertiary-fixed': 'var(--wm-tertiary-fixed)',
        'inverse-surface': 'var(--wm-inverse-surface)',
        'secondary-fixed-dim': 'var(--wm-secondary-fixed-dim)',
        'surface-container-highest': 'var(--wm-surface-container-highest)',
        'surface-container-lowest': 'var(--wm-surface-container-lowest)',
        'on-primary-container': 'var(--wm-on-primary-container)',
        'on-background': 'var(--wm-on-background)',
        'on-secondary-fixed': 'var(--wm-on-secondary-fixed)',
        'on-tertiary-fixed-variant': 'var(--wm-on-tertiary-fixed-variant)',
        'on-secondary': 'var(--wm-on-secondary)',
        'on-secondary-fixed-variant': 'var(--wm-on-secondary-fixed-variant)',
        'tertiary-container': 'var(--wm-tertiary-container)',
        'tertiary-fixed-dim': 'var(--wm-tertiary-fixed-dim)',
        surface: 'var(--wm-surface)',
        'on-error-container': 'var(--wm-on-error-container)',
        'on-tertiary-fixed': 'var(--wm-on-tertiary-fixed)',
        'on-primary': 'var(--wm-on-primary)',
        'error-container': 'var(--wm-error-container)',
        'secondary-fixed': 'var(--wm-secondary-fixed)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '3rem',
        'margin-page': '1.5rem',
        'gutter-default': '1.25rem',
        'gutter-compact': '0.75rem',
      },
      fontFamily: {
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'code-tabular': ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '700' }],
        'body-lg': ['15px', { lineHeight: '22px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'body-md': ['13px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'code-tabular': ['12px', { lineHeight: '16px', letterSpacing: '0em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
